Binder/Binder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Twitter/', include('Twitter.urls')),
    url(r'^Courses/', include('cp.urls')),
    url(r'^Hospital/', include('rtc.urls')),
    url(r'^', include('alpha.urls')),
    url(r'^FoodShare/', include("discussions.urls", namespace='posts')),

]

Binder/Twitter/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name= 'Twitter'

urlpatterns = [
    url(r'^$', views.index, name='main'),
    url(r'^all/$', views.alltweet, name='all'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^(?P<tweet_id>[0-9]+)/comment/$', views.commentadd, name='addcomment'),
    url(r'^profile/$', views.profile, name='profile'),
]

Binder/cp/urls.py
from django.conf.urls import url
from . import views

app_name='cp'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.loginuser, name='login'),
    url(r'^logout/$', views.logoutuser, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^view/(?P<course_id>[0-9]+)/$', views.viewlist, name='viewlist'),
    url(r'^add/(?P<course_id>[0-9]+)/$', views.add, name='add'),
    url(r'^documents/(?P<filter_by>[a-zA_Z]+)/$', views.documents, name='documents'),

]

Binder/Twitter/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
# Create your models here.

class useradd(User):
    country = models.CharField(max_length = 100)
    profile_picture = models.FileField()

class useradmin(admin.ModelAdmin):
    list_display = ['id', 'country', 'profile_picture']


class tweet(models.Model):
    text = models.CharField(max_length=1000)
    tweetto = models.ManyToManyField(useradd)
    tweetfrom = models.ForeignKey(useradd, related_name='+', on_delete=models.CASCADE, null=True)
    timestamp = models.TimeField(auto_now_add=True, blank=True)

class tweetadmin(admin.ModelAdmin):
    list_display = ['id', 'text', 'tweetfrom', 'timestamp']

class comment(models.Model):
    ctext = models.CharField(max_length=1000)
    commenton = models.ForeignKey(tweet, on_delete=models.CASCADE)
    commentfrom = models.ForeignKey(useradd, on_delete=models.CASCADE, null=True, related_name='commentw')
    timestamp = models.TimeField(auto_now_add=True, blank=True)

Binder/comment/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
# from discussions.models import post
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType




class CommentManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id)
        return qs
class comment(models.Model):
    user = models.ForeignKey(User, editable=True, blank=False, null=True)
    content = models.TextField(default='')
    # post = models.ForeignKey(post)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id = models.PositiveIntegerField(blank=False, null=True)
    objects = CommentManager()
    def __str__(self):
        return str(self.user.username)

Binder/Twitter/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import useradd, tweet, comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    profile_picture = forms.FileField(required=False)

    class Meta:
        model = useradd
        fields = ['username', 'email', 'password', 'country', 'profile_picture']
        help_texts = None

class TweetForm(forms.ModelForm):

    class Meta:
        model = tweet
        fields = ['text', 'tweetto']

class CommentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ['ctext']

Binder/comment/forms.py
from django import forms

class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    # parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea)

Binder/Twitter/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import tweet, useradd, comment
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import UserForm, TweetForm, CommentForm

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        form = TweetForm(request.POST or None, request.FILES or None)
        userses = request.user
        if form.is_valid():
            tfrom = request.user.username
            fetch_obj= useradd.objects.filter(username=tfrom)[0]
            tweetfrom = fetch_obj
            text  = form.cleaned_data['text']
            tweetto = form.cleaned_data['tweetto']
            '''if(request.FILES.items()):
                smiley = request.FILES['smiley']
            else:
                smiley=None'''
            temp_obj = tweet()
            temp_obj.text = text
            temp_obj.tweetfrom = tweetfrom
            temp_obj.save()
            for item in tweetto:
                temp_obj.tweetto.add(item)
            temp_obj.save()
            form = TweetForm(None)


        context = {
            "form": form,
            "all_tweets" : tweet.objects.all()[:5],
            "user1":useradd.objects.get(username=request.user.username),
            "comment":comment.objects.all(),
            "usercount":len(useradd.objects.all())
        }
        return render(request, 'index.html', context)
    else:
        return render(request, 'login.html')

def register(request):
    if(not request.user.is_authenticated):
        form = UserForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            usern = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            usern.set_password(password)
            usern.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    form = TweetForm(None)
                    userses = request.user
                    context={
                        "form":form,
                        "all_tweets": tweet.objects.all()[:5],
                        "user1":useradd.objects.get(username=request.user.username),
                        "usercount":len(useradd.objects.all())
                    }
                    return render(request, 'index.html', context)
        context = {
            "form": form
        }
        return render(request, 'register.html', context)
    else:
        form = TweetForm(None)
        userses = request.user
        context = {
            "form": form,
            "all_tweets": tweet.objects.all()[:5],
            "usercount": len(useradd.objects.all()),
            "user1":useradd.objects.get(username=userses.username)
        }
        return render(request, 'index.html', context)


def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                form = TweetForm(None)
                context = {
                    "form": form,
                    "all_tweets": tweet.objects.all()[:5],
                    "usercount": len(useradd.objects.all()),
                    "user1":useradd.objects.get(username=request.user.username)
                }
                return render(request, 'index.html', context)
            else:
                return render(request, 'login.html', {"error_message":"Your account has been suspended."})
        else:
            return render(request, 'login.html', {"error_message": "Invalid Login Details."})
    elif request.user.is_authenticated:
        form = TweetForm(None)
        context = {
            "form": form,
            "all_tweets": tweet.objects.all()[:5],
            "usercount": len(useradd.objects.all()),
            "user1":useradd.objects.get(username=request.user.username)
        }
        return render(request, 'index.html', context)
    else:
        return render(request, 'login.html')

def user_logout(request):
    logout(request)
    return render(request, 'login.html')

def commentadd(request, tweet_id):
    form = CommentForm(request.POST or None)
    message=""
    if form.is_valid():
        newcomment = form.save(commit=False)
        cmfrom = request.user.username
        fetch_obj = useradd.objects.filter(username=cmfrom)[0]
        newcomment.commentfrom = fetch_obj
        newcomment.commenton = tweet.objects.get(pk=tweet_id)
        newcomment.save()
        message="Successfully added a comment"
    context = {
        'form':form,
        "user1": useradd.objects.get(username=request.user.username),
        "message":message
    }
    return render(request, 'comment.html', context)

def alltweet(request):
    if request.user.is_authenticated:
        context = {
            "all_tweets" : tweet.objects.all(),
            "user1":useradd.objects.get(username=request.user.username),
            "comment":comment.objects.all()
        }
        return render(request, 'all.html', context)
    else:
        return render(request, 'login.html')

def profile(request):
    context={
        "user1":useradd.objects.get(username=request.user.username),
    }
    return render(request, 'profile.html', context)

Binder/comment/views.py
from django.shortcuts import render

# Create your views here.

Binder/Twitter/templates/all.html
{% extends 'base.html' %}
{% block msgactive %}active{% endblock %}
{% block navbar %}Tweets{% endblock %}
{% block body %}
<div class="row">
<div class="col-md-12">
    </div>
    </div>
<div class="row">
<div class="col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-header">
          All Tweets
        </div>
        <div class="card-body">
            {% for tweets in all_tweets %}
          <div class="media social-post">
  <div class="media-left">
    <a href="#">
      <img src="../../media/{{ tweets.tweetfrom.profile_picture }}">
    </a>
  </div>
  <div class="media-body">
    <div class="media-heading">
      <h4 class="title" style="font-weight: bold;">{{ tweets.tweetfrom }}</h4>
      <h5 class="timeing">{{ tweets.timestamp }}</h5>
    </div>
    <div class="media-content">{{tweets.text}}</div>
    <div class="media-content">Tags:{% for tweetto in tweets.tweetto.all %}
    <a href="">#{{ tweetto }}</a>
    {% endfor %}</div>
    <div class="media-action">
      <a href="{% url 'Twitter:addcomment' tweets.id %}"><button class="btn btn-link"><i class="fa fa-comments-o"></i> Comments:</button></a>
    </div>
  {% for comments in comment %}
    {% if comments.commenton == tweets  %}
    <div class="media-left col-md-1">
    <a href="#">
      <img src="../../media/{{ comments.commentfrom.profile_picture }}">
    </a>
    </div>
    <div class="media-body">
      <div class="media-heading">
      <h4 class="title" style="font-weight: bold;">{{ comments.commentfrom }}</h4>
      <h5 class="timeing">{{ comments.timestamp }}</h5>
    </div>
    <div class="media-content" style="font-size: 13px;">{{ comments.ctext }}</div>
    </div>
      {% endif %}
      {% endfor %}
    <div class="media-comment">
    <div>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
      Add Comment
      </button>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Type in your Comment:</h4>
          </div>
          <div class="modal-body">
            <iframe src="{% url 'Twitter:addcomment' tweets.id %}" width="100%"></iframe>
            </div>
          <div class="modal-footer">
            <a href="{% url 'Twitter:main' %}"><button type="button" class="btn btn-sm btn-default">Close</button></a>
          </div>
        </div>
      </div>
    </div>

    </div>
  </div>
</div>
            {% endfor %}
        </div>
      </div>
    </div>

</div>
<div class="row">
</div>
{% endblock %}

Binder/Twitter/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>CampusTwitter</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'Twitter/vendor.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Twitter/flat-admin.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <script>
  var text=["Keep Tweeting!"];
  console.log(text[0]);
  $(document).ready(function(){
    var i = 0;
    var n = 14;
    var k="";
    function nextFrame() {
        if(i < n) {
            console.log(text[0][i]);
            k+=text[0][i];
            $('#title').html(k).show();
            i++;
            // Continue the loop in 0.3s
            setTimeout(nextFrame, 300);
        }
        if(i==n){
          $('#title').append(' &#9829;').show();
          i+=1;
        }
    }
    setInterval(nextFrame, 1000);


  });
  </script>

</head>
<body>
  <div class="app app-default">

<aside class="app-sidebar" id="sidebar">
  <div class="sidebar-header">
    <a class="sidebar-brand" href="{% url 'Twitter:main' %}">Campus<span class="highlight">Twitter</span></a>
    <div id="title" style="text-align: center;font-size: 20px;font-family: Satisfy;color: #c88027;"></div>
    <button type="button" class="sidebar-toggle">
      <i class="fa fa-times"></i>
    </button>
  </div>
  <div class="sidebar-menu">
    <ul class="sidebar-nav">
      <li class="{% block dashactive %}{% endblock %}">
        <a href="{% url 'Twitter:main' %}">
          <div class="icon">
            <i class="fa fa-tasks" aria-hidden="true"></i>
          </div>
          <div class="title">Dashboard</div>
        </a>
      </li>
      <li class="{% block msgactive %}{% endblock %}">
        <a href="{% url 'Twitter:all' %}">
          <div class="icon">
            <i class="fa fa-comments" aria-hidden="true"></i>
          </div>
          <div class="title">Tweets</div>
        </a>
      </li>
      <li class="{% block profileactive %}{% endblock %}">
        <a href="{% url 'Twitter:profile' %}">
          <div class="icon">
            <i class="fa fa-user" aria-hidden="true"></i>
          </div>
          <div class="title">User</div>
        </a>
      </li>
    </ul>
  </div>
  <div class="sidebar-footer">

  </div>
</aside>

<script type="text/ng-template" id="sidebar-dropdown.tpl.html">
  <div class="dropdown-background">
    <div class="bg"></div>
  </div>
  <div class="dropdown-container">
    {{list}}
  </div>
</script>
<div class="app-container">

  <nav class="navbar navbar-default" id="navbar">
  <div class="container-fluid">
    <div class="navbar-collapse collapse in">
      <ul class="nav navbar-nav navbar-mobile">
        <li>
          <button type="button" class="sidebar-toggle">
            <i class="fa fa-bars"></i>
          </button>
        </li>
        <li class="logo">
          <a class="navbar-brand" href="{% url 'Twitter:main' %}">Campus<span class="highlight"> Twitter</span></a>
        </li>
        <li>
          <button type="button" class="navbar-toggle">
            <img class="profile-img" src="../media/{{ user1.profile_picture }}">
          </button>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li class="navbar-title">{% block navbar %}{% endblock %}</li>
        <!--
        <li class="navbar-search hidden-sm">
          <input id="search" type="text" placeholder="Search..">
          <button class="btn-search"><i class="fa fa-search"></i></button>
        </li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown notification danger">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <div class="icon"><i class="fa fa-bell" aria-hidden="true"></i></div>
            <div class="title">Notifications</div>
            <div class="count">2</div>
          </a>
          <div class="dropdown-menu">
            <ul>
              <li class="dropdown-header">Notification</li>
              <li>
                <a href="#">
                  <span class="badge badge-danger pull-right">1</span>
                  <div class="message">
                    <div class="content">
                      <div class="title">New Tweet</div>
                      <div class="description"></div>
                    </div>
                  </div>
                </a>
              </li>
            </ul>
          </div>
        </li>
        <li class="dropdown profile">
          <a href="{% url 'Twitter:profile' %}" class="dropdown-toggle"  data-toggle="dropdown">
            <img class="profile-img" src="../../media/{{ user1.profile_picture }}">
            <div class="title">Profile</div>
          </a>
          <div class="dropdown-menu">
            <div class="profile-info">
              <h4 class="username" style="text-transform: capitalize">{{ user1.username }}</h4>
            </div>
            <ul class="action">
              <li>
                <a href="{% url 'Twitter:profile' %}">
                  Profile
                </a>
              </li>
              <li>
                <a href="{% url 'Twitter:logout' %}">
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <!--
<div class="btn-floating" id="help-actions">
  <div class="btn-bg"></div>
  <button type="button" class="btn btn-default btn-toggle" data-toggle="toggle" data-target="#help-actions">
    <i class="icon fa fa-plus"></i>
    <span class="help-text">Shortcut</span>
  </button>
  <div class="toggle-content">
    <ul class="actions">
      <li><a href="https://github.com/p-mayank" target="_blank"><i class="fa fa-github" aria-hidden="true"></i>&nbsp;&nbsp;GitHub</a></li>
      <li><a href="https://www.linkedin.com/in/mayank96" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i>&nbsp;&nbsp;LinkedIn</a></li>
      <li><a href="https://www.facebook.com/pmayank96" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i>&nbsp;&nbsp;Facebook</a></li>
    </ul>
  </div>
</div>-->
    {% block body %}
    
    {% endblock %}
    <div class="row">
  </div>
  <footer class="app-footer">
  <div class="row">
    <div class="col-xs-12">
      <div class="footer-copyright">
        Copyright &#9400 Mayank
      </div>
    </div>
  </div>
</footer>
</div>

  </div>

  <script type="text/javascript" src="{% static 'Twitter/JS/vendor.js' %}"></script>
  <script type="text/javascript" src="{% static 'Twitter/JS/app.js' %}"></script>

</body>
</html>

Binder/Twitter/templates/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CampusTwitter</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Twitter/vendor.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Twitter/flat-admin.css' %}">
</head>
<style>
    .center_div{
    margin: 0 auto;
    width:80% /* value of your choice which suits your alignment */
}
</style>
<body>
<div class="container">
<div class="center_div">

<div class="row">
<div class="col-sm-offset-2 text-center">
<h4>{{ message }}</h4>
<form method="POST" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
      {% endfor %}
    <br><br><button class="btn btn-primary col-sm-offset-2">Add Comment!</button>
    </form><br><br><br><br>


</div>
    <div class="col-sm-2 col-sm-offset-5">
        <a href="{% url 'Twitter:main' %}"><button type="button" class="btn btn-success">Go back!</button></a>
    </div>
</div>

</div>
</div>
</body>
</html>

Binder/Twitter/templates/index.html
{% extends 'base.html' %}
{% block dashactive %}active{% endblock %}
{% block navbar %}Dashboard{% endblock %}
{% block body %}
<div class="row">
<div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <i class="fa fa-twitter" style="font-size: 1.5em;color: skyblue"></i>
          <div style="padding-left: 10px">
          New Tweet:</div>
        </div>
        <div class="card-body">
          <div class="row">
  <div class="col-md-6">
  <form method="POST" action="{% url 'Twitter:main' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-md-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-md-10">{{ field }}</div>
    </div>
      {% endfor %}
    <button class="btn btn-success">Tweet</button>
    </form>
  </div>
</div>
        </div>
      </div>
    </div>
    </div>
<div class="row">
<div class="col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-header">
          Recent Tweets
          <div class="col-sm-offset-9">
          <a href="{% url 'Twitter:all' %}"><strong>View All</strong></a>
          </div>
        </div>
        <div class="card-body">
            {% for tweets in all_tweets %}
          <div class="media social-post">
  <div class="media-left">
    <a href="#">
      <img src="../../media/{{ tweets.tweetfrom.profile_picture }}">
    </a>
  </div>
  <div class="media-body">
    <div class="media-heading">
      <h4 class="title" style="font-weight: bold;">{{ tweets.tweetfrom }}</h4>
      <h5 class="timeing">{{ tweets.timestamp }}</h5>
    </div>
    <div class="media-content">{{tweets.text}}</div>
    <div class="media-content">Tags:{% for tweetto in tweets.tweetto.all %}
    <a href="">#{{ tweetto }}</a>
    {% endfor %}</div>
    <div class="media-action">
      <a href="{% url 'Twitter:addcomment' tweets.id %}"><button class="btn btn-link"><i class="fa fa-comments-o"></i> Comments:</button></a>
    </div>
  {% for comments in comment %}
    {% if comments.commenton == tweets  %}
    <div class="media-left col-md-1">
    <a href="#">
      <img src="../../media/{{ comments.commentfrom.profile_picture }}">
    </a>
    </div>
    <div class="media-body">
      <div class="media-heading">
      <h4 class="title" style="font-weight: bold;">{{ comments.commentfrom }}</h4>
      <h5 class="timeing">{{ comments.timestamp }}</h5>
    </div>
    <div class="media-content" style="font-size: 13px;">{{ comments.ctext }}</div>
    </div>
      {% endif %}
      {% endfor %}
    <div class="media-comment">
    <div>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
      Add Comment
      </button>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Type in your Comment:</h4>
          </div>
          <div class="modal-body">
            <iframe src="{% url 'Twitter:addcomment' tweets.id %}" width="100%"></iframe>
            </div>
          <div class="modal-footer">
            <a href="{% url 'Twitter:main' %}"><button type="button" class="btn btn-sm btn-default">Close</button></a>
          </div>
        </div>
      </div>
    </div>

    </div>
  </div>
</div>
            {% endfor %}
        </div>
      </div>
    </div>

</div>
</a>

  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 col-md-offset-4" style="padding-left: 90px">
      <a class="card card-banner card-yellow-light">
  <div class="card-body">
    <i class="icon fa fa-user-plus fa-4x" style="font-size: 2.5em"></i>
    <div class="content">
      <div class="title">New Registrations</div>
      <div class="value" style="font-size: 2em"><span class="sign"></span>{{ usercount }}</div>
    </div>
  </div>
</a>

  </div>
</div>
{% endblock %}

Binder/Twitter/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>LoginPage</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'Twitter/template.css' %}">

</head>

<body class="hold-transition login-page">
<div class="login-box">
<div class="login-logo">
    <a href="{% url 'Twitter:main' %}">Campus<b>Twitter</b></a>
  </div>
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
      {% if error_message %}
        <p class="text-danger" style="text-align: center; font-size: larger">{{ error_message }}</p>
      {% endif %}

    <form method="post" action="{% url 'Twitter:login' %}" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="Username" name="username" id="username">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="password" id="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
    <a href="{% url 'Twitter:register' %}" class="text-center">Register as a new member</a>

  </div>
  <!-- /.login-box-body -->
</div>
</body>
<!--
<form method="post" action="" enctype="multipart/form-data">

    Username:<br>
    <input type="text" id="username" name="username"><br>
    Password:<br>
    <input type="password" id="password" name="password"><br>
    <button type="submit">Submit</button>
</form>-->
</html>

Binder/Twitter/templates/profile.html
{% extends 'base.html' %}
{% block navbar %}Profile{% endblock %}
{% block profileactive %}active{% endblock %}
{% block body %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Profile Details:</div>
            <div class="card-body">
                <div class="media social-post">
                    <div class="media-left">
                        <a href="#">
                            <img src="../../media/{{ user1.profile_picture }}">
                        </a>
                    </div>
                    <div class="media-body">
    <div class="media-heading">
      <h4 class="title" style="font-weight: bold;">{{ user1.username }}</h4>
      <h5 class="timeing">{{ user1.email }}</h5>
    </div>
        </div>
    </div>
</div>

{% endblock %}