Binder/Binder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Twitter/', include('Twitter.urls')),
    url(r'^Courses/', include('cp.urls')),
    url(r'^Hospital/', include('rtc.urls')),
    url(r'^', include('alpha.urls')),
    url(r'^FoodShare/', include("discussions.urls", namespace='posts')),

]

Binder/alpha/urls.py
from django.conf.urls import url
from discussions import views as dviews
from . import views

app_name='alpha'

urlpatterns = [
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^home/$', dviews.post_list, name='list'),
]

Binder/cp/urls.py
from django.conf.urls import url
from . import views

app_name='cp'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.loginuser, name='login'),
    url(r'^logout/$', views.logoutuser, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^view/(?P<course_id>[0-9]+)/$', views.viewlist, name='viewlist'),
    url(r'^add/(?P<course_id>[0-9]+)/$', views.add, name='add'),
    url(r'^documents/(?P<filter_by>[a-zA_Z]+)/$', views.documents, name='documents'),

]

Binder/discussions/urls.py
from django.conf.urls import url
from . import views

app_name='discussions'

urlpatterns = [
    url(r'^$', views.post_list, name="list"),
    url(r'index/$', views.index),
    url(r'^(?P<id>\d+)/$', views.post_detail, name="detail"),
    url(r'^(?P<id>\d+)/edit/$', views.edit_post),
    url(r'^(?P<id>\d+)/delete/$', views.post_delete),
    url(r'create/$', views.create_post, name='create_post'),
    url(r'profile/$', views.profile, name='profile'),


]

Binder/discussions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.text import slugify
from comment.models import comment
from django.contrib.contenttypes.models import ContentType


class post(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField(default='')
    goingat = models.CharField(max_length=10, default='')
    comingback = models.CharField(max_length=10, default='')
    # slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    writer = models.ForeignKey(User, editable=True, blank=False, null=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title
    def __str__(self):
        return self.content
    def __unicode__(self):
        return self.content
    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id":self.id})
    def get_url_to_list(self):
        return "/discussions/"
    @property
    def comments(self):
        instance = self
        qs = comment.objects.filter_by_instance(instance)
        return qs
    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance)
        return content_type

Binder/discussions/forms.py
from django import forms

from .models import post

class post_form(forms.ModelForm):
    class Meta:
        model = post
        fields = {
            "title",
            "content",
            "goingat",
            "comingback"
        }

        def __init__(self, *args, **kwargs):
            super(post_form, self).__init__(*args, **kwargs)
            self.fields.keyOrder = ['content', 'option','title',"goingat","comingback"]

Binder/discussions/views.py
from django.shortcuts import render, get_object_or_404, redirect,HttpResponse
from django.http import HttpResponseRedirect
from .models import post
from .forms import post_form
from django.db.models import Q
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from comment.forms import CommentForm
from comment.models import comment



def index(request):
    return render(request, "discussions/practise.html")



def post_detail(request, id):
    queryset = get_object_or_404(post, id=id)
    writer = queryset.writer

    # content_type = ContentType.objects.get_for_model(post)
    initial_data = {
        "content_type": queryset.get_content_type,
        "object_id": queryset.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if request.method == "POST":
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/login')
    if form.is_valid():
        # print(form.cleaned_data)
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        new_comment, created = comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data
        )

    comments = queryset.comments
    context = {
        "obj": queryset,
        "comments": comments,
        "comment_form": form,
        "writer": writer
    }
    return render(request, "discussions/post_detail.html", context)

def create_post(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login')
    form = post_form(request.POST or None)
    message=""
    if form.is_valid():
        instance = form.save(commit=False)
        instance.writer = request.user
        instance.save()
        message = "Successfully added the post!"
    context = {
        "form": form,
        "message":message
    }
    return render(request, "discussions/create_post.html", context)

def edit_post(request, id):

    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login')
    instance = get_object_or_404(post, id=id)
    form = post_form(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        # messages.success(request, "Successfully created")
        return HttpResponseRedirect(instance.get_url_to_list())
    # else:
    #     messages.error(request, "Unsuccessful ")

    context = {
        "form": form
    }
    return render(request, "discussions/create_post.html", context)

# def search_post_list(request):



def post_list(request):
    posts = post.objects.all().order_by("-timestamp")

    search_query = request.GET.get("q")
    if search_query:
        posts = posts.filter(Q(title__icontains=search_query) | Q(content__icontains=search_query) | Q(goingat__icontains = search_query) | Q(comingback__icontains = search_query) )
    context = {
        "post": posts,
    }
    return render(request, "discussions/post_list.html", context)




def post_delete(request, id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login')
    var = get_object_or_404(post,id=id)
    var.delete()
    return redirect("posts:list")

def profile(request):
    return render(request, 'discussions/profile.html')

Binder/discussions/templates/discussions/base.html
<!DOCTYPE html>
<html>
<head>
  <title>CabShare</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'discussions/vendor.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'discussions/flat-admin.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <script>
  var text=["Eat 'n Sleep!"];
  console.log(text[0]);
  $(document).ready(function(){
    var i = 0;
    var n = 13;
    var k="";
    function nextFrame() {
        if(i < n) {
            console.log(text[0][i]);
            k+=text[0][i];
            $('#title').html(k).show();
            i++;
            // Continue the loop in 0.3s
            setTimeout(nextFrame, 300);
        }
        if(i==n){
          $('#title').append(' &#9829;').show();
          i+=1;
        }
    }
    setInterval(nextFrame, 1000);


  });
  </script>

</head>
<body>
  <div class="app app-default">

<aside class="app-sidebar" id="sidebar">
  <div class="sidebar-header">
    <a class="sidebar-brand" href="#"><span class="highlight">Food</span>Share</a>
    <div id="title" style="text-align: center;font-size: 20px;font-family: Satisfy;color: #c88027;"></div>
    <button type="button" class="sidebar-toggle">
      <i class="fa fa-times"></i>
    </button>
  </div>
  <div class="sidebar-menu">
    <ul class="sidebar-nav">
      <li class="{% block dashactive %}{% endblock %}">
        <a href="{% url 'discussions:list' %}">
          <div class="icon">
            <i class="fa fa-tasks" aria-hidden="true"></i>
          </div>
          <div class="title">Dashboard</div>
        </a>
      </li>
      <li class="{% block profileactive %}{% endblock %}">
        <a href="{% url 'discussions:profile' %}">
          <div class="icon">
            <i class="fa fa-user" aria-hidden="true"></i>
          </div>
          <div class="title">User</div>
        </a>
      </li>
    </ul>
  </div>
  <div class="sidebar-footer">

  </div>
</aside>

<script type="text/ng-template" id="sidebar-dropdown.tpl.html">
  <div class="dropdown-background">
    <div class="bg"></div>
  </div>
  <div class="dropdown-container">
    {{list}}
  </div>
</script>
<div class="app-container">

  <nav class="navbar navbar-default" id="navbar">
  <div class="container-fluid">
    <div class="navbar-collapse collapse in">
      <ul class="nav navbar-nav navbar-mobile">
        <li>
          <button type="button" class="sidebar-toggle">
            <i class="fa fa-bars"></i>
          </button>
        </li>
        <li class="logo">
          <a class="navbar-brand" href="{% url 'discussions:list' %}"><span class="highlight">Food</span>Share</a>
        </li>
        <li>
          <button type="button" class="navbar-toggle">
                <div class="icon">
                    <i class="fa fa-user fa-3x" aria-hidden="true"></i>
                </div>
          </button>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li class="navbar-title">{% block title %}{% endblock %}</li>
        <!--
        <li class="navbar-search hidden-sm">
          <input id="search" type="text" placeholder="Search..">
          <button class="btn-search"><i class="fa fa-search"></i></button>
        </li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown profile">
          <a href="{% url 'discussions:profile' %}" class="dropdown-toggle"  data-toggle="dropdown">
            <div class="icon" style="text-align: center">
            <i class="fa fa-user fa-2x" aria-hidden="true"></i>
                <div style="text-transform: capitalize;text-align: center"> {{ request.user.username }}</div>
          </div>
            <div class="title">Profile</div>
          </a>
          <div class="dropdown-menu">
            <div class="profile-info">
              <h4 class="username" style="text-transform: capitalize">{{ request.user.username }}</h4>
            </div>
            <ul class="action">
              <li>
                <a href="{% url 'discussions:profile' %}">
                  Profile
                </a>
              </li>
              <li>
                <a href="{% url 'alpha:logout' %}">
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

    {% block body %}

    {% endblock %}

    <div class="row">
  </div>
  <footer class="app-footer">
  <div class="row">
    <div class="col-xs-12">
      <div class="footer-copyright">
        Copyright &#9400 IIT Guwahati
      </div>
    </div>
  </div>
</footer>
</div>

  </div>

  <script type="text/javascript" src="{% static 'discussions/JS/vendor.js' %}"></script>
  <script type="text/javascript" src="{% static 'discussions/JS/app.js' %}"></script>

</body>
</html>

Binder/discussions/templates/discussions/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Food Share</title>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'discussions/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'discussions/css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'discussions/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'discussions/js/bootstrap.min.js' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'discussions/js/jquery.min.js' %}">
</head>
<body style="background-color: #f4f6f6;">
	<div class="container-fluid">
	<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
	<h3 style="text-align: center;">Add the Details:</h3>
	<br>
    {% if message %}
        <h5 class="text-success">{{ message }}</h5>
    {% endif %}
	<form method="POST" action="">
        {% csrf_token %}
        {% for field in form %}
	<div class="row">
        {% if field.errors %}
        <div class="col-md-12" style="text-align: center">
            {{ field.errors }}
        </div>
        {% endif %}
	<div class="col-md-6"><b>{{ field.label_tag }}</b></div>
	<div class="col-md-6">
		<div class="form-group">
            {{ field }}
        </div>
	</div>
	</div>
    {% endfor %}
    <button type="submit" class="btn btn-success" name="action">Submit</button>
	</form>
	<div class="col-md-2"></div>
	</div>
	</div>
    </div>
</body>
</html>

Binder/discussions/templates/discussions/post_detail.html
{% extends 'discussions/base.html' %}
{% block dashactive %}active{% endblock %}
{% block title %}Dashboard{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-6 center">
            <a href="{% url 'discussions:list' %}"><button type="button" class="btn btn-success">Back</button></a>
        </div>
        <div class="col-md-12">
            <div class="card">
                {% load crispy_forms_tags %}
                    {% if user.is_authenticated %}
                        {% if user == writer %}
                            <div class="card-header">
                                <a href="/discussions/{{ obj.id }}/edit" class="btn  btn-primary btn-large login_now col-md-2 col-md-offset-3">Edit Post</a>
                                <a href="/discussions/{{ obj.id }}/delete" class="btn  btn-primary btn-large login_now col-md-2 col-md-offset-1">Delete Post</a>
                            </div>
                        {% endif %}
                    {% endif %}
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2 col-md-offset-4"><b>Title:</b></div>
                        <div class="col-md-6">{{ obj.title }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-2 col-md-offset-4"><b>Content:</b></div>
                        <div class="col-md-6">{{ obj.content }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-2 col-md-offset-4"><b>GoingTo:</b></div>
                        <div class="col-md-6">{{ obj.goingat }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-2 col-md-offset-4"><b>ComingBack:</b></div>
                        <div class="col-md-6">{{ obj.comingback }}</div>
                    </div>
                    <hr/>
                    <div class="row">
                        <div class="col-md-2">
                        <b>Comments:<br/><br/></b>
                            </div>
                    </div>
                    {% for comment in comments %}
                        <div class="media-left col-md-1">
                        <a href="#">
                          <div class="icon">
                                <i class="fa fa-user fa-3x" aria-hidden="true"></i>
                          </div>
                        </a>
                        </div>
                        <div class="media-body">
                          <div class="media-heading">
                          <h4 class="title" style="font-weight: bold;">{{ comment.user }}</h4>
                          <h5 class="timeing">{{ comment.timestamp|timesince }} ago</h5>
                        </div>
                        <div class="media-content" style="font-size: 13px;">{{ comment.content }}</div>
                        </div>
                    {% endfor %}
                    <hr/>
                    <div class="row">
                        <div class="col-md-2">
                        <b>Add a Comment:<br/><br/></b>
                            </div>
                    </div>
                    <form id="icon_prefix2" class="materialize-textarea" method="POST" action="." >
                        {% csrf_token %}
                                {{ comment_form }}
                        <br/>
                        <button type="submit" class="btn btn-success" value="Post Comment">Post Comment</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

Binder/discussions/templates/discussions/post_list.html
{% extends 'discussions/base.html' %}
{% block dashactive %}active{% endblock %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="row">
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <form  method="GET" action="" >
                                    <div class="col-md-6">
                                        <input type="text" name="q" class="form-control" placeholder="Search post..." /></div>
                                    <div class="col-md-6">
                                        <button  class="btn btn-success" type="submit" name="action">Search</button></div>
            </form>
        </div>
    </div>
</div>
<div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <i class="fa fa-twitter" style="font-size: 1.5em;color: skyblue"></i>
          <div style="padding-left: 10px">
          New Post:</div>
        </div>
        <div class="card-body">
          <div class="row">
  <div class="col-md-6">
  <div class="media-comment">
    <div>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal1">
      Add New
      </button>
    </div>
    <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header"  style="background-color: #e7edee">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Feed in your new Post:</h4>
          </div>
          <div class="modal-body">
            <iframe src="{% url 'discussions:create_post' %}" width="100%" style="height: 300px;"></iframe>
            </div>
          <div class="modal-footer">
            <a href="{% url 'discussions:list' %}"><button type="button" class="btn btn-sm btn-default">Close</button></a>
          </div>
        </div>
      </div>
    </div>

    </div>
  </div>
</div>
        </div>
      </div>
    </div>
    </div>
<div class="row">
<div class="col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-header">
          Feeds
        </div>
        <div class="card-body">
        {% if post.count == 0 %}
            <div class="center text-danger">No posts to display!</div>
        {% endif %}
            {% for obj in post %}
          <div class="media social-post">
          <div class="media-left">
    <a href="#">
      <div class="icon">
          <i class="fa fa-user fa-3x" aria-hidden="true"></i>
      </div>
    </a>
  </div>
  <div class="media-body">
    <div class="media-heading">
        <a href='{{ obj.get_absolute_url }}'><h3 class="box-title">{{ obj.title }}</h3> </a>
      <h4 class="title" style="font-weight: bold;text-transform: capitalize;">{{ obj.writer }}</h4>
      <h5 class="timeing">{{ obj.timestamp }}</h5>
    </div>
    <div class="media-content">{{obj.content}}</div>
    <div class="media-content">Tags:
    <a href="">#GoingTo:{{ obj.goingat }};</a>
        <a href="">#ComingBack:{{ obj.comingback }}</a>
    </div>
  </div>
</div>
            {% endfor %}
        </div>
      </div>
    </div>

</div>
{% endblock %}

Binder/discussions/templates/discussions/profile.html
{% extends 'discussions/base.html' %}
{% block profileactive %}active{% endblock %}
{% block title %}Profile{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="card" style="height: 250px;">
                <div class="card-header">
                    <div style="padding-left: 10px"><b>User Profile</b></div>
                </div>
                <div class="card-body">
                    <div class="col-md-2">
                        <a href="#">
                          <div class="icon">
                              <i class="fa fa-user fa-5x" aria-hidden="true"></i>
                          </div>
                        </a>
                    </div>
                    <div class="col-md-9" style="text-transform: capitalize;font-size: 20px;">
                        <b>User: </b>{{ request.user.username }} <br/><br/>
                        <b>Webmail: </b>{{ request.user.email }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}