Binder/Binder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Twitter/', include('Twitter.urls')),
    url(r'^Courses/', include('cp.urls')),
    url(r'^Hospital/', include('rtc.urls')),
    url(r'^', include('alpha.urls')),
    url(r'^FoodShare/', include("discussions.urls", namespace='posts')),

]

Binder/cp/urls.py
from django.conf.urls import url
from . import views

app_name='cp'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.loginuser, name='login'),
    url(r'^logout/$', views.logoutuser, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^view/(?P<course_id>[0-9]+)/$', views.viewlist, name='viewlist'),
    url(r'^add/(?P<course_id>[0-9]+)/$', views.add, name='add'),
    url(r'^documents/(?P<filter_by>[a-zA_Z]+)/$', views.documents, name='documents'),

]

Binder/cp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models


class loguser(models.Model):
    user = models.ForeignKey(User,default=1)
    is_prof = models.BooleanField(default=False)

class course(models.Model):
    user = models.ManyToManyField(User, related_name='courses', null=True)
    title = models.CharField(max_length=100)

class document(models.Model):
    course = models.ForeignKey(course, on_delete=models.CASCADE, null=True)
    book_link = models.CharField(max_length=1000, default=None)
    lecture = models.FileField(default=None)
    tutorial = models.FileField(default=None)
    postedby = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

Binder/cp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import loguser, document


from django.core.exceptions import ValidationError

def set_field_html_name(cls, new_name):
    old_render = cls.widget.render
    def _widget_render_wrapper(name, value, attrs=None):
        return old_render(new_name, value, attrs)
    cls.widget.render = _widget_render_wrapper

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields= ['username', 'password', 'email']

class DocumentsForm(forms.ModelForm):
    book_link = forms.CharField(required=False)
    lecture = forms.FileField(required=False)
    tutorial = forms.FileField(required=False)
    set_field_html_name(lecture,'lecture_file')
    set_field_html_name(tutorial, 'tutorial_file')

    class Meta:
        model = document
        fields = ['book_link', 'lecture', 'tutorial']

Binder/cp/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .forms import UserForm, DocumentsForm
from .models import loguser, course, document
# Create your views here.

def loginuser(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                courses = course.objects.filter(user=request.user)
                return render(request, 'cp/index.html', {'courses':courses})
            else:
                return render(request, 'cp/login.html', {'error_message':'Your account has been disabled!'})
        else:
            return render(request, 'cp/login.html', {'error_message':'Invalid Credentials!'})
    return render(request, 'cp/login.html')

def logoutuser(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'cp/login.html', context)

def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                courses = course.objects.filter(user=request.user)
                return render(request, 'cp/index.html', {'courses':courses})
    context={
        "form":form
    }
    return render(request, 'cp/register.html', context)

def viewlist(request, course_id):
    if not request.user.is_authenticated():
        return render(request, 'cp/login.html')
    else:
        user = request.user
        courses = get_object_or_404(course, pk=course_id)
        poster=""
        for k in courses.document_set.all():
            poster = k.postedby
            break
        return render(request, 'cp/detail.html', {'courses':courses, 'user':user, 'poster':poster})

def add(request, course_id):
    form = DocumentsForm(request.POST or None, request.FILES or None)
    courses = get_object_or_404(course, pk=course_id)
    poster = ""
    for k in courses.document_set.all():
        poster = k.postedby
        break
    if form.is_valid():
        documents = courses.document_set.all()
        documentnew = form.save(commit=False)
        documentnew.course = courses
        if 'lecture_file' in request.FILES.keys():
            documentnew.lecture = request.FILES['lecture_file']
        if 'tutorial_file' in request.FILES.keys():
            documentnew.tutorial = request.FILES['tutorial_file']
        documentnew.postedby = request.user
        documentnew.save()
        return render(request, 'cp/detail.html', {'courses':courses, 'poster':poster})
    context={
        'courses':courses,
        'form':form,
        'poster':poster
    }
    return render(request, 'cp/create_document.html', context)

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'cp/login.html')
    else:
        courses = course.objects.filter(user=request.user)
        document_results = document.objects.all()
        query = request.GET.get("q")
        if query:
            courses = courses.filter(
                Q(title__icontains=query)
            ).distinct()
            document_results = document_results.filter(
                Q(book_link__icontains=query) |
                Q(lecture__icontains=query) |
                Q(tutorial__icontains=query)
            ).distinct()
            return render(request, 'cp/index.html', {
                'courses': courses,
                'documents': document_results,
            })
        return render(request, 'cp/index.html', {'courses':courses})

def documents(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'cp/login.html')
    else:
        try:
            document_ids = []
            for courses in course.objects.filter(user=request.user):
                for documentss in courses.document_set.all():
                    document_ids.append(documentss.pk)
            users_documents = document.objects.filter(pk__in=document_ids)
        except courses.DoesNotExist:
            users_documents = []
        return render(request, 'cp/songs.html', {
            'document_list': users_documents,
            'filter_by': filter_by,
        })

Binder/cp/templates/cp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CoursePortal{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'cp/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'cp/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'cp:index' %}">CoursePortal</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'cp:index' %}">Courses</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'cp:documents' 'all' %}">Documents</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'cp:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'cp:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Binder/cp/templates/cp/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CoursePortal{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'cp/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'cp/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'cp:index' %}">CoursePortal</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'cp:signup' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'cp:login' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Binder/cp/templates/cp/create_document.html
{% extends 'cp/base.html' %}
{% block title %}Add a New Document{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'cp:viewlist' courses.id %}">
                                <h3>Course Template</h3>
                        </a>
                    <h1>{{ courses.title }}</h1>
                    <h2 style="text-transform: capitalize">{{ poster }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'cp:viewlist' courses.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'cp:add' courses.id %}">Add New Document</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Document</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ courses }}">
                        {% include 'cp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

Binder/cp/templates/cp/detail.html
{% extends 'cp/base.html' %}
{% block title %}{{ courses }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'cp:viewlist' courses.id %}">
                            <h3>CourseTemplate</h3>
                    </a>
                    <h1>{{ courses.title }}</h1>
                    <h4 style="text-transform: capitalize">Professor: {{ poster }}</h4>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'cp:viewlist' courses.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'cp:add' courses.id %}">Add New Document</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Documents</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Tutorial</th>
                            <th>Lecture</th>
                            <th>EBook</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for document in courses.document_set.all %}
                            <tr>
                            {% if document.tutorial %}
                                <td><a target="_blank" href="{{ document.tutorial.url }}">Tutorial File(*.pdf)</a></td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                            {% if document.lecture %}
                                <td><a target="_blank" href="{{ document.lecture.url }}">Lecture File(*.pdf)</a></td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                                <td>
                                    {% if document.book_link %}
                                        {{ document.book_link }}
                                        {% else %}
                                        No Link Uploaded
                                    {% endif %}
                                    </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

Binder/cp/templates/cp/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

Binder/cp/templates/cp/index.html
{% extends 'cp/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3 style="text-transform: capitalize">{{ user.username }}'s Courses</h3>
        </div>
        {% if courses %}
            {% for course in courses %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'cp:viewlist' course.id %}">
                            <h4>CourseTemplate</h4>
                        </a>
                        <div class="caption">
                            <h2>{{ course.title }}</h2>
                            <!-- View Details -->
                            <a href="{% url 'cp:viewlist' course.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if documents %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Documents</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Course Title</th>
                                    <th>Tutorial</th>
                                    <th>Lectures</th>
                                    <th>BookLink</th>
                                    <th>PostedBy</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for document in documents %}
                                    <tr>
                                        <td>{{ document.course.title }}</td>
                                        <td><a target="_blank" href="{{ document.tutorial.url }}">Tutorial</a></td>
                                        <td>
                                            <td><a target="_blank" href="{{ document.lecture.url }}">Lecture</a></td>
                                        <td>
                                            <td>{{ document.book_link }}</td>
                                        <td>{{ document.postedby }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

Binder/cp/templates/cp/login.html
{% extends 'cp/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'cp:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'cp:signup' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Binder/cp/templates/cp/register.html
{% extends 'cp/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'cp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'cp:login' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Binder/cp/templates/cp/songs.html
{% extends 'cp/base.html' %}
{% block title %}All Documents{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'cp:documents' 'all' %}">View All</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Tutorial</th>
                            <th>Lecture</th>
                            <th>EBook</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for document in courses.document_set.all %}
                            <tr>
                                <td><a target="_blank" href="{{ document.tutorial.url }}">Tutorial</a></td>
                                <td><a target="_blank" href="{{ document.lecture.url }}">Lecture</a></td>
                                <td>
                                    {% if document.book_link %}
                                        {{ document.book_link }}
                                        {% else %}
                                        No Link Uploaded
                                    {% endif %}
                                    </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}